server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      routes:
        - id: historial-service
          uri: lb://historial-service
          predicates:
            - Path=/historial/**
            
        - id: vehiculo-service
          uri: lb://vehiculo-service
          predicates:
            - Path=/vehiculo/**
            
        - id: reparaciones-service
          uri: lb://reparaciones-service
          predicates:
            - Path=/reparaciones/**
            
        - id: reportes-service
          uri: lb://reportes-service
          predicates:
            - Path=/reportes/**

        
