server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: historial-service
          uri: lb://historial-service
          predicates:
            - Path=/historial/**
        - id: reparaciones-service
          uri: lb://reparaciones-service
          predicates:
            - Path=/reparaciones/**
        - id: reportes-service
          uri: lb://reportes-service
          predicates:
            - Path=/reportes/**
        - id: vehiculo-service
          uri: lb://vehiculo-service
          predicates:
            - Path=/vehiculo/**

       globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true