server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/historialDB
    username: postgres
    password: moshiluna_1620
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
